sudo: required #is required to use the docker service in travis ci

language: minimal

dist: jammy
addons:
  apt:
    sources:
      - sourceline: "deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    packages:
      - docker

services:
  - docker

script:
  - docker --version

after_success:
  - bash docker_push.sh
