version: "3.3" # https://kompose.io/conversion/
services:
  reverseproxy:
    image: reverseproxy
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - backend_user
      - backend_feed
  backend_user:
    image: udagram-api-user
    # volumes: # delete me
    #   - ./udagram-api-user:/usr/src/app # delete me
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
    # depends_on: # delete me
    #   - postgres # delete me
  backend_feed:
    image: udagram-api-feed
    # volumes: # delete me
    #   - ./udagram-api-feed:/usr/src/app # delete me
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_REGION: $AWS_REGION
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
    # depends_on: # delete me
    #   - postgres # delete me
  frontend:
    image: udagram-frontend:local
    ports:
      - "8100:80"
    labels:
      kompose.service.expose: true
  # DELETE BELOW
  # postgres:
  #   image: postgres:14-alpine
  #   volumes:
  #     - ./data/db:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: $POSTGRES_USERNAME
  #     POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  #     POSTGRES_DB: $POSTGRES_DB
