version: "3.3" # https://kompose.io/conversion/
services:
  reverseproxy:
    image: reverseproxy
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - backend-user
      - backend-feed
  backend-user:
    image: udagram-api-user
    # volumes: # for local dev
    #   - ./udagram-api-user:/usr/src/app # for local dev
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
    # depends_on: # for local dev
    #   - postgres # for local dev
  backend-feed:
    image: udagram-api-feed
    # volumes: # for local dev
    #   - ./udagram-api-feed:/usr/src/app # for local dev
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_REGION: $AWS_REGION
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
    # depends_on: # for local dev
    #   - postgres # for local dev
  frontend:
    image: udagram-frontend:local
    ports:
      - "8100:80"
  # postgres: # for local dev
  #   image: postgres:14-alpine # for local dev
  #   volumes: # for local dev
  #     - ./data/db:/var/lib/postgresql/data # for local dev (do not create ./data on first run)
  #   ports: # for local dev
  #     - 5432:5432 # for local dev
  #   environment: # for local dev
  #     POSTGRES_USER: $POSTGRES_USERNAME # for local dev
  #     POSTGRES_PASSWORD: $POSTGRES_PASSWORD # for local dev
  #     POSTGRES_DB: $POSTGRES_DB # for local dev
