apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-09-20T12:13:06Z"
  name: backend-feed
  namespace: default
  resourceVersion: "30531"
  uid: 75eaadcb-1589-4ffb-8a78-3fcc43bca5c1
spec:
  clusterIP: 10.100.95.181
  clusterIPs:
  - 10.100.95.181
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: backend-feed
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
