# kubectl autoscale deployment my-app-2 --cpu-percent=50 --min=1 --max=2
# kubectl get hpa
# worker node role
# https://www.youtube.com/watch?v=aZd0UolVwD4
# node group We recommend setting 2 minimum nodes, 3 maximum nodes
# update apiHost in frontend > environment.ts
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
    spec:
      restartPolicy: Always
      containers:
        - name: frontend
          imagePullPolicy: Always
          image: ifaniry/udagram-frontend:v1.2
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 512m
            requests:
              cpu: 256m

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: frontend

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
