# kubectl autoscale deployment my-app-2 --cpu-percent=50 --min=1 --max=2
# kubectl get hpa
# worker node role
# https://www.youtube.com/watch?v=aZd0UolVwD4
# node group We recommend setting 2 minimum nodes, 3 maximum nodes
# update apiHost in frontend > environment.ts
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    run: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  - targetPort: 80
    protocol: TCP
  selector:
    run: frontend
